trigger:
  branches:
    include:
      - main

resources:
  - repo: self

variables:
  IMAGE_TAG: 'indigosour/rscraper_worker:1.0.$(Build.BuildId)'

jobs:
  - job: build_and_push
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - task: DockerInstaller@0
        displayName: 'Install Docker'

      - task: Docker@2
        displayName: 'Docker Login'
        inputs:
          command: login
          containerRegistry: 'DockerHub_Connection'
          repository: 'indigosour/rscraper_worker'

      - task: Docker@2
        displayName: 'Build and Push Docker Image'
        inputs:
          command: buildAndPush
          repository: 'indigosour/rscraper_worker'
          dockerfile: '**/Dockerfile'
          tags: |
            $(Image_Tag)
            latest
          noCache: true